adminUser:
  password: vault:pr-23-9-boot-local/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-23-9-boot-local/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-23-9-boot-local/prow:hmacToken
